---
title: "Fun time with R programming"
author: "Charles Kwame Appiah"
date: "`r Sys.Date()`"
output:
  html_document: default
  code_download: true
  theme: journal
  df_print: paged
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r Ex.1a}
# importing packages
library(tidyverse)
library(magrittr)

x = c(rnorm(1:100), NA)

# removing missing value and sum the rest
x %>% sum(na.rm = TRUE)

set.seed(123) # For reproducibility

# Generate 1000 random samples, filter out negatives, and compute mean
sample_positive <- c(rnorm(1:1000), NA)
mean_positive <- mean(na.omit(sample_positive))

# Print result
print(mean_positive)
```

```{r Ex.1b}
#library(dplyr)

# Sample data frame with true values (t) and predicted values (y)
data <- data.frame(
  x = c(3, 5, 2, 8, 7),
  y = c(2.5, 5.3, 1.8, 7.5, 6.9)
)

# Compute RMSE using a pipeline
rmse <- data %>% mutate(sq_diff = (x - y)^2) %>%  
  # Compute squared differences
  summarise(mean_sq_diff = mean(sq_diff)) %>%  
  # Compute mean squared difference
  pull(mean_sq_diff) %>%  # Extract value
  sqrt()  # Compute square root

# Print the RMSE
print(rmse)
```
```{r}
data = data.frame (s = c(3,4,5,6,7,8,9,1), 
                   t = c(4,5,6,7,8,9,10,11))

# Compute the RMSE using a pipeline 
rmse = data %>%
  mutate(sq_diff = (s - t)**2) %>%
  summarise(mean_sq_diff = mean(sq_diff)) %>%
  pull(mean_sq_diff) %>% sqrt()

# Print the RMSE
print(rmse)
```

```{r cache_random.Ex.2a, cache=TRUE}
set.seed(1234)  # Ensures reproducibility initially
random_numbers <- as.data.frame(rnorm(100))  # Generate 100 random values
head(random_numbers)# Display first few numbers

#??set.seed 
```


```{r Ex.2b}
mean_random <- mean(random_numbers)
mean_random  # Compute and display the mean
```

```{r Ex.3}
# import dataset from csv file
kyphosis_data = read.csv("C:/Users/HP/Desktop/Data Science/Machine learning/kyphosis.csv")

kyphosis_data %>% head()

kyphosis_data %>% summary
```
# Group_by  

```{r Summarise}
kyphosis_data %>% group_by(Kyphosis) %>% summarise(mean.Age =mean(Age))

kyphosis_data %>% group_by(Kyphosis) %>%summarise(mean.Number =mean(Number))

kyphosis_data %>% group_by(Kyphosis) %>% summarise(mean.Start =mean(Start))
```

# Visualization

```{r qplot, warning=FALSE}
kyphosis_data %>% qplot(Age, Number, data=., col = Kyphosis)

kyphosis_data %>% qplot (Age, Start, data = ., col = Kyphosis)

kyphosis_data %>% qplot (bins = 10, Number, data = ., col = Kyphosis)
```


```{r Sel, warning=FALSE}
kyphosis_data$Kyphosis %>% unique 

# convert to tibble
as_tibble(kyphosis_data)

# Selecting Kyphosis and Age column only
kyphosis_data %>% tbl_df %>% select(Kyphosis,Age) %>% head()

# Selecting Kyphosis and Number column only
kyphosis_data %>% tbl_df %>% select(Kyphosis,Number) %>%head()

# Selecting Kyphosis and Start column only
kyphosis_data %>% tbl_df %>% select(Kyphosis,Start) %>%head()
```

```{r A.N, warning=FALSE}
# Selecting Age and Number column only
kyphosis_data %>% tbl_df %>% select(Age, Number) %>% head()

# Selecting Age and Start column only
kyphosis_data %>% tbl_df %>% select(Age, Start) %>% head()
```

```{r Sel only e, warning=FALSE}
# Selecting column containing  only letter "e"
kyphosis_data %>% tbl_df %>% select(contains("e")) %>% head()

# Selecting column starting with only letter "k"
kyphosis_data %>% tbl_df %>% select(starts_with("k")) %>%  head()
```

```{r only t, warning=FALSE}
# Select only letter ending with "t"
kyphosis_data %>% tbl_df %>% select(ends_with("t")) %>% head()

# Select only letter matching with "o"
kyphosis_data %>% tbl_df %>%select(matches("o")) %>% head()

# Select only letter matching with "s"
kyphosis_data %>% tbl_df %>%select(matches("s")) %>% head()

# Select only letter not starting with "s"
kyphosis_data %>% tbl_df %>%select(-starts_with("s")) %>% head()
```

```{r A+N, warning=FALSE}
# creating a new column 
kyphosis_data %>% tbl_df %>% mutate(Age.plus.Number = Age + Number) %>% select(Kyphosis, Age.plus.Number) %>% head()

kyphosis_data %>% tbl_df %>% mutate(Age.plus.Start = Age + Start) %>% select(Kyphosis, Age.plus.Start) %>% head()
```

```{r A.N.S, warning=FALSE}
kyphosis_data %>% tbl_df %>%
 mutate(Age.plus.Number = Age + Number, Age.plus.Start = Age + Start) %>% select (Kyphosis, Age.plus.Number, Age.plus.Start ) %>% head()
```

```{r without select, warning=FALSE}
# Combining Age and Number to create Age.plus.Number
# Combining Age and Start to create Age.plus.Start
kyphosis_data %>% tbl_df %>% transmute(Kyphosis,Age.plus.Number = Age + Number, Age.plus.Start = Age + Start) %>%head()
```

```{r Age_arrange, warning=FALSE}
# Arrange Age from smallest to largest
kyphosis_data %>% tbl_df %>% arrange(Age) %>% head()

# Arrange Number from smallest to largest
kyphosis_data %>% tbl_df %>% arrange(Number) %>% head()

# Arrange Start from smallest to largest
kyphosis_data %>% tbl_df %>% arrange(Start) %>% head()

# Arrange Age from largest to smallest
kyphosis_data %>% tbl_df %>% arrange(desc(Age)) %>% head()
```

```{r filter_Age, warning=FALSE}
# Filter values >= 45 in Age column
kyphosis_data %>% tbl_df %>% filter(Age >= 45) %>% head()

# Filter values >= 5 in Number column
kyphosis_data %>% tbl_df %>% filter(Number >= 5) %>% head()

# Filter values >= 3 in Start column
kyphosis_data %>% tbl_df %>% filter(Start >= 10) %>% head()
```

```{r  Number < 5, warning=FALSE}
# Filter Age values >= 5 and also has Kyphosis
kyphosis_data %>% tbl_df %>%filter(Age >= 5 & Kyphosis == "present") %>% select(Kyphosis, Age) %>% head()

# Filter Number values < 5 and also has Kyphosis
kyphosis_data %>% tbl_df %>%filter(Number < 5 & Kyphosis == "present") %>%select(Kyphosis, Number) %>% head()

# Filter Start values < 5 and also has Kyphosis
kyphosis_data %>% tbl_df %>%filter(Start < 5 & Kyphosis == "present") %>%select(Kyphosis, Start) %>% head()
```

```{r Kyphosis group, warning=FALSE}
kyphosis_data %>% tbl_df %>% group_by(Kyphosis) %>% head()
```

```{r total_row}
# Count the number of observation in the dataset
kyphosis_data %>% summarise(Observations = n())
```

```{r Persons, warning=FALSE}
# Counting the number of persons with Kyphosis
kyphosis_data %>% group_by(Kyphosis) %>% summarise(Number.Of.Persons = n())
```

```{r Persons.Mean}
# Counting the number of persons with Kyphosis according to mean Age
kyphosis_data %>% group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Mean_Age = mean(Age))

# Counting the number of persons with Kyphosis according to mean Number
kyphosis_data %>%group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Mean_Numbers = mean(Number))

# Counting the number of persons with Kyphosis according to mean Start
kyphosis_data %>%group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Mean_Start = mean(Start))
```

```{r Persons.Medain}
# Counting the number of persons with Kyphosis according to median Age
kyphosis_data %>% group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Median_Age = median(Age))

# Counting the number of persons with Kyphosis according to median Number
kyphosis_data %>%group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Median_Numbers = median(Number))

# Counting the number of persons with Kyphosis according to median Start
kyphosis_data %>%group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Median_Start = median(Start))
```

```{r Std.Persons}
# Counting the number of persons with Kyphosis according to Age standard deviation 
kyphosis_data %>% group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Std.Age = sd(Age))

# Counting the number of persons with Kyphosis according to Number standard deviation 
kyphosis_data %>%group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Std.Numbers = sd(Number))

# Counting the number of persons with Kyphosis according to Start standard deviation
kyphosis_data %>%group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Std.Start = sd(Start))
```

```{r}
# Counting the number of persons with Kyphosis according to Age variance
kyphosis_data %>% group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Var_Age = var(Age))

# Counting the number of persons with Kyphosis according to Number variance
kyphosis_data %>%group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Var_Numbers = var(Number))

# Counting the number of persons with Kyphosis according to Start variance
kyphosis_data %>%group_by(Kyphosis) %>% summarise(Number.Of.Persons = n(), Var_Start = var(Start))
```
# Boxplot of the dataset

```{r plot.ex}
kyphosis_data %>% select(Kyphosis, Age) %>%
 qplot(Kyphosis, Age, geom = "boxplot", data = ., col = Kyphosis)

kyphosis_data %>% select(Kyphosis, Number) %>%
 qplot(Kyphosis, Number, geom = "boxplot", data = ., col = Kyphosis)

kyphosis_data %>% select(Kyphosis, Start) %>%
 qplot(Kyphosis, Start, geom = "boxplot", data = ., col = Kyphosis)
```

```{r}
kyphosis_data %>% gather(key = Attribute, value = Measurement,Age) %>% select(Kyphosis, Attribute, Measurement) %>% head()

kyphosis_data %>% gather(key = Attribute, value = Measurement,Age) %>% select(Kyphosis, Attribute, Measurement) %>% head()%>% qplot(Attribute, Measurement, geom = "boxplot", facets = . ~ Kyphosis, data = ., col = Kyphosis)
```


```{r}
kyphosis_data %>% gather(key = Attribute, value = Measurement,Number) %>% select(Kyphosis, Attribute, Measurement) %>% head()

kyphosis_data %>% gather(key = Attribute, value = Measurement,Number) %>% select(Kyphosis, Attribute, Measurement) %>% head() %>% qplot(Attribute, Measurement, geom = "boxplot", facets = . ~ Kyphosis, data = ., col = Kyphosis)
```

```{r}
kyphosis_data %>% gather(key = Attribute, value = Measurement,Start) %>% select(Kyphosis, Attribute, Measurement) %>% head()

kyphosis_data %>% gather(key = Attribute, value = Measurement,Start) %>% select(Kyphosis, Attribute, Measurement) %>% head()%>% qplot(Attribute, Measurement, geom = "boxplot", facets = . ~ Kyphosis, data = ., col = Kyphosis)
```

```{r mpg}
as_tibble(mpg)
```

```{r blue.green}
kyphosis_data %>% lm(Age ~ Number, data = .) %>% plot

kyphosis_data %>% plot(Number ~ Age, data = ., type = 'p')
kyphosis_data %>% lines(Start ~ Age, data = ., type = "p",col = "blue")

kyphosis_data %$% plot(Number ~ Age, type = 'p', ylim = range(c(Number, Start)))
kyphosis_data %>% lines(Start ~ Age, data = ., type = "p" , col = "green")

as_tibble(kyphosis_data)
```

```{r red}
kyphosis_data %>% plot(Number ~ Age, data = ., xlab = "Age", ylab = "Number", main = "Age Against Number")
kyphosis_data %>% lm(Number ~ Age, data = .) %>% abline(col = "red")
```

```{r Density}
kyphosis_data %>% qplot (Age, data = ., geom = "density", col = Kyphosis)

kyphosis_data %>% qplot (Number, data = ., geom = "density", col = Kyphosis)

kyphosis_data %>% qplot (Start, data = ., geom = "density", col = Kyphosis)
```

```{r ggplot}
# Bar plot
kyphosis_data %>% ggplot + geom_bar(aes( x = Start,
 color = Kyphosis))

# Area plot
kyphosis_data %>% ggplot + geom_area(aes(x=Age, y = Start, colour =  Kyphosis))
```

```{r density.hist}
kyphosis_data %>% ggplot(aes(x = Age, y = after_stat(count))) + geom_histogram(bins = 10) + geom_density()

kyphosis_data %>% ggplot(aes(x = Number, y = after_stat(count))) + geom_histogram(bins = 10) + geom_density()

kyphosis_data %>% ggplot(aes(x = Start, y = after_stat(count))) + geom_histogram(bins = 10) + geom_density() 
```

```{r loess.lm}
kyphosis_data %>% ggplot(aes(x = Age, y = Number)) +
 geom_point() + geom_smooth( method = "loess",formula =  y ~ x)

kyphosis_data %>% ggplot(aes(x = Age, y = Number)) +
 geom_point() + geom_smooth( method = "lm",formula =  y ~ x)
```

```{r tidy}
kyphosis_data %>% gather(key, value, Age, Number) %>%
 ggplot(aes(x = Kyphosis, y = value)) + geom_line() +
 facet_grid(key ~ ., scale = "free_y")

kyphosis_data %>% gather(key, value, Age, Number) %>%
 ggplot(aes(x = Kyphosis, y = value)) + geom_point() +
 facet_grid(key ~ ., scale = "free_y")
```

```{r facet_grid}
kyphosis_data %>% gather(Measurement, Value, -Kyphosis) %>%
 ggplot(aes(x = Kyphosis, y = Value)) + geom_boxplot() +
 facet_grid(Measurement ~ ., scale = "free_y") # row-wise 

kyphosis_data %>% gather(Measurement, Value, -Kyphosis) %>%
 ggplot(aes(x = Kyphosis, y = Value)) + geom_boxplot() +
 facet_grid(. ~ Measurement, scale = "free_y") 
```

```{r scale.reverse}
kyphosis_data %>% ggplot(aes(x = Age, y = Number)) + geom_point() + geom_smooth(method = "lm", formula =  y ~ x) + scale_x_continuous("Age") + scale_y_continuous("Number")

kyphosis_data %>% ggplot(aes(x = Age, y = Number)) + geom_point() + geom_smooth(method = "lm", formula =  y ~ x) + scale_x_reverse("Age") + scale_y_reverse("Number")
```

```{r jitter}
kyphosis_data %>% ggplot(aes(x = Kyphosis, y = Age)) +
 geom_boxplot() + geom_jitter(width = 0.1, height = 0.1) 

kyphosis_data %>% ggplot(aes(x = Kyphosis, y = Number)) +
 geom_boxplot() + geom_jitter(width = 0.1, height = 0.1) 

kyphosis_data %>% ggplot(aes(x = Kyphosis, y = Start)) +
 geom_boxplot() + geom_jitter(width = 0.1, height = 0.1) 
```

```{r fill_manual}
kyphosis_data %>% gather(Measurement, Value, -Kyphosis) %>%
 ggplot(aes(x = Kyphosis, y = Value, fill = Kyphosis)) +
 geom_boxplot() + scale_fill_manual(values = c("red", "green")) + facet_grid(Measurement ~ ., scale = "free_y")
```
```{r fill_brewer}
kyphosis_data %>% gather(Measurement, Value, -Kyphosis) %>%
 ggplot(aes(x = Kyphosis, y = Value, fill = Kyphosis)) +
 geom_boxplot() + scale_fill_brewer(palette = "Greens") +
 facet_grid(Measurement ~ ., scale = "free_y")

kyphosis_data %>% gather(Measurement, Value, -Kyphosis) %>%
 ggplot(aes(x = Kyphosis, y = Value, fill = Kyphosis)) +
 geom_boxplot() + scale_fill_brewer(palette = "Reds") +
 facet_grid(Measurement ~ ., scale = "free_y")

kyphosis_data %>% gather(Measurement, Value, -Kyphosis) %>%
 ggplot(aes(x = Kyphosis, y = Value, fill = Kyphosis)) +
 geom_boxplot() + scale_fill_brewer(palette = "Blues") +
 facet_grid(Measurement ~ ., scale = "free_y")
```

```{r}
kyphosis_data %>% gather(Measurement, Value, -Kyphosis) %>%
 ggplot(aes(x = Kyphosis, y = Value, fill = Kyphosis)) +
 geom_boxplot() + scale_x_discrete(labels = c("absent" = "Absent", "present" = "Present")) + scale_fill_brewer(palette = "Blues") + facet_grid(Measurement ~ ., switch = "y") + coord_flip()

kyphosis_data %>% gather(Measurement, Value, -Kyphosis) %>%
 ggplot(aes(x = Kyphosis, y = Value, fill = Kyphosis)) +
 geom_boxplot() + scale_x_discrete(labels = c("absent" = "Absent", "present" = "Present")) + scale_fill_brewer(palette = "Blues") + facet_grid(Measurement ~ ., switch = "y", scale = "free_x") + coord_flip() + theme(strip.background = element_blank()) + theme(legend.position = "top")
```
### Random Sampling

```{r}
# Sample 10 of the dataset
kyphosis_data %>% sample_n(10) %>% summary()

# Sample 20% of the dataset
kyphosis_data %>% sample_frac(0.2) %>% summary()
```

```{r}
library(pryr)
# Checking the memory usage of the dataset
mem_change(kyphosis_data)
```

```{r Samp_10.0.5}
kyphosis_data %>% sample_n(10) %>% ggplot + geom_point(aes(x = Age, y = Number)) 

kyphosis_data %>% sample_frac(0.5) %>% ggplot + geom_point(aes(x = Age, y = Number)) 
```

```{r density_2D}
kyphosis_data %>% sample_n(10) %>% ggplot(aes(x = Age, y = Number)) + geom_density_2d()

kyphosis_data %>% sample_frac(.05) %>% ggplot(aes(x = Age, y = Number)) + geom_density_2d()
```

```{r hexbin}
kyphosis_data %>% sample_n(10) %>% ggplot(aes(x = Age, y = Number)) + geom_hex()

kyphosis_data %>% sample_frac(.05) %>% ggplot(aes(x = Age, y = Number)) + geom_hex()

kyphosis_data %>% ggplot(aes(x = Age, y = Number)) + geom_hex() + scale_fill_gradient(low = "lightgray", high = "red") + geom_density2d(color = "black")
```

```{r}
data(cars)
# creating a polynomial function
cars %>% model.matrix(dist ~ speed + I(speed^2) + I(speed**3) + I(speed**4), data = .) %>% head 

# creating a linear function 
cars %>% lm(dist ~ speed + I(speed^2) + I(speed**3) + I(speed**4), data = .) %>% summary

cars %>% ggplot(aes(x = speed, y = dist)) + geom_point(col = "brown") +
 geom_smooth(method = "lm", formula = y ~ x + I(x^2) + I(x^3) + I(x^4))
```
### Find the root mean square error

```{r}
rmse <- function(x,t) sqrt(mean(sum((t - x)^2)))

# split the dataset into training 50% and testing 50%
training_data <- cars[1:25,]
test_data <- cars[26:50,] 

line <- training_data %>% lm(dist ~ speed, data = .)
poly <- training_data %>% lm(dist ~ speed + I(speed^2) + I(speed**3) + I(speed**4), data = .) 

# predicting the error on the linear and polynomial function
rmse(predict(line, test_data), test_data$dist) 
rmse(predict(poly, test_data), test_data$dist) 

sampled_cars <- cars %>% mutate(training = sample(0:1, nrow(cars), replace = TRUE))
sampled_cars %>% head 
```


```{r}
# Load necessary libraries
library(ggplot2)
library(caret)
library(datasets)


# Load the cars dataset
data(cars)

# Set seed for reproducibility
set.seed(123)

# Split data into training (70%) and test (30%)
trainIndex <- sample(1:nrow(cars), size = 0.7 * nrow(cars), replace = FALSE)

trainData <- cars[trainIndex, ]
testData <- cars[-trainIndex, ]

get_poly_error <- function(degree, trainData, testData) {
  # Ensure column names are referenced explicitly
  if (!"speed" %in% names(trainData)) stop("Column 'speed' not found in trainData")
  if (!"speed" %in% names(testData)) stop("Column 'speed' not found in testData")

  # Fit polynomial model
  model <- lm(dist ~ poly(speed, degree), data = trainData)

  # Predict on training and test data
  trainPred <- predict(model, newdata = trainData)
  testPred <- predict(model, newdata = testData)

  # Compute RMSE
  trainRMSE <- sqrt(mean((trainData$dist - trainPred)^2))
  testRMSE <- sqrt(mean((testData$dist - testPred)^2))

  return(c(degree, trainRMSE, testRMSE))
}

# Run for degrees 1 to 10 using lapply for better handling
results <- as.data.frame(do.call(rbind, lapply(1:10, function(d) get_poly_error(d, trainData, testData))))
colnames(results) <- c("Degree", "Train_RMSE", "Test_RMSE")


# Find the degree with the lowest test RMSE
best_degree <- results$Degree[which.min(results$Test_RMSE)]
best_degree <- results$Degree[which.max(results$Test_RMSE)]

# Print results and best degree
print(results)
cat("\nBest generalization occurs at polynomial degree:", best_degree, "\n")

# Plot the RMSE values
ggplot(results, aes(x = Degree)) +
  geom_line(aes(y = Train_RMSE, color = "Train RMSE")) +
  geom_line(aes(y = Test_RMSE, color = "Test RMSE")) +
  labs(title = "Polynomial Degree vs RMSE", x = "Polynomial Degree", y = "RMSE") +
  scale_color_manual(values = c("Train RMSE" = "blue", "Test RMSE" = "red")) + theme_minimal()

ggsave(filename = gc("Cap.jpeg"), dpi = 320, scale = 1, bg = "lightgreen" )
```

## Machine learning
### Logistic Regression

```{r}
data <- cars

data
```


```{r}
# Load necessary libraries
library(mlbench)  # For Breast Cancer dataset
library(caret)    # For data partitioning
#library(dplyr)    # For data manipulation

# Load Breast Cancer dataset

data(BreastCancer)


BreastCancer <- BreastCancer[, -1]  # Remove ID column
BreastCancer <- na.omit(BreastCancer)  # Remove rows with missing values

# Convert Class column to a factor (Malignant = 1, Benign = 0)
BreastCancer$Class <- factor(ifelse(BreastCancer$Class == "malignant", 1, 0), levels = c(1, 0))

# Split dataset into training (70%) and testing (30%)
set.seed(123)
trainIndex <- createDataPartition(BreastCancer$Class, p = 0.7, list = FALSE)

trainData <- BreastCancer[trainIndex, ]
testData <- BreastCancer[-trainIndex, ]

# Function to fit a logistic regression model
train_logistic_model <- function(trainData) {
  glm(Class ~ ., data = trainData, family = binomial)
}

# Function to make predictions and evaluate performance
predict_summary <- function(model, data) {
  # Predict probabilities
  probs <- predict(model, newdata = data, type = "response")
  # Convert to binary (threshold = 0.5)
  preds <- ifelse(probs > 0.5, "Malignant", "Benign")
  actuals <- as.factor(data$Class)

  # Compute evaluation metrics
  cm <- table(Predicted = preds, Data = actuals)
  accuracy <- sum(diag(cm)) / sum(cm)
  precision <- cm[2, 2] / sum(cm[2, ])
  recall <- cm[2, 2] / sum(cm[, 2])
  f1_score <- 2 * (precision * recall) / (precision + recall)

  return(list(ConfusionMatrix = cm, Accuracy = accuracy, Precision = precision, Recall = recall, F1_Score = f1_score))
}

# Train the model
model <- train_logistic_model(trainData)

# Evaluate on training data
train_results <- predict_summary(model, trainData)
print("Training Set Performance:")
print(train_results)

# Evaluate on test data
test_results <- predict_summary(model, testData)
print("Test Set Performance:")
print(test_results)
```
### Decision tree
```{r warning=FALSE}
# Load necessary libraries
library(mlbench)   # Contains BreastCancer dataset
library(caret)     # For data splitting and cross-validation
library(rpart)     # For decision tree
library(rpart.plot) # For tree visualization

# Load dataset
data("BreastCancer")

# Remove ID column and handle missing values
BreastCancer <- BreastCancer[, -1]  # Remove ID column
BreastCancer <- na.omit(BreastCancer)  # Remove rows with missing values

# Convert target variable to factor
BreastCancer$Class <- as.factor(BreastCancer$Class)

# Split data into training (70%) and test (30%)
set.seed(123)
trainIndex <- createDataPartition(BreastCancer$Class, p = 0.7, list = FALSE)

trainData <- BreastCancer[trainIndex, ]
testData <- BreastCancer[-trainIndex, ]

# Train Decision Tree model
model <- rpart(Class ~ ., data = trainData, method = "class")

# Make predictions on train dat
pred = predict(model, trainData, type = "class")

# Make predictions on test data
predictions <- predict(model, testData, type = "class")

# Evaluate model using confusion matrix
cv = confusionMatrix(pred, trainData$Class)
print(cv)

conf_matrix <- confusionMatrix(predictions, testData$Class)
print(conf_matrix)

# Perform 10-fold Cross-Validation
ctrl <- trainControl(method = "cv", number = 10)
cv_model <- train(Class ~ ., data = trainData, method = "rpart", trControl = ctrl)

# Print Cross-Validation Results
print(cv_model)

# Plot Decision Tree
rpart.plot(model, main = "Decision Tree for Breast Cancer Classification")
```

### Random Forest

```{r}
# Load necessary libraries
library(mlbench)
library(randomForest)
library(caret)

# Load the Breast Cancer dataset
data("BreastCancer")

# Remove the ID column
BreastCancer$Id <- NULL  

# Convert target variable to factor
BreastCancer$Class <- as.factor(BreastCancer$Class)

# Convert explanatory variables to numeric (except the target)
BreastCancer[, -10] <- lapply(BreastCancer[, -10], function(x) as.numeric(as.character(x)))

# Handle missing values by removing rows with NAs
BreastCancer <- na.omit(BreastCancer)

# Set seed for reproducibility
set.seed(123)

# Split data into training (70%) and testing (30%)
trainIndex <- createDataPartition(BreastCancer$Class, p = 0.7, list = FALSE)
trainData <- BreastCancer[trainIndex, ]
testData <- BreastCancer[-trainIndex, ]

# Train the Random Forest model
rf_model <- randomForest(Class ~ ., data = trainData, ntree = 500, mtry = 3, importance = TRUE)

# Make predictions on test data
rf_train <- predict(rf_model, trainData)
rf_predictions <- predict(rf_model, testData)

# Evaluate accuracy
confusionMatrix(rf_train, trainData$Class)
confusionMatrix(rf_predictions, testData$Class)

# Perform Cross-Validation using caret
control <- trainControl(method = "cv", number = 10)  # 10-fold cross-validation
cv_model <- train(Class ~ ., data = BreastCancer, method = "rf", trControl = control)

# Print cross-validation results
print(cv_model)
```
### Neural Network
```{r}
library(nnet)
model <- cars %>% nnet(dist ~ speed, data = ., size = 5)
rmse(predict(model, cars), cars$dist)

model <- BreastCancer %>% nnet(Class ~ Cl.thickness, data = ., size = 50)

predict(model, BreastCancer) %>% head 

predicted_class <- predict(model, BreastCancer) %>%
 { ifelse(. < 0.7, "benign", "malignant") }
 
table(BreastCancer$Class, predicted_class) %>% head

(accuracy = sum(diag(table(BreastCancer$Class, predicted_class))) / sum((table(BreastCancer$Class, predicted_class))))
```

```{r letter-a, echo = FALSE}
#library(nycflights13)

library(learnr)

#flights
question("What number is the letter A in the English alphabet?",
  answer("8"),
  answer("14"),
  answer("1", correct = TRUE),
  answer("23")
)

```

```{r radio, echo = FALSE}
question_radio(
  "Is this a good question?",
  answer("yes", correct = TRUE),
  answer("no", message = 'This is a good question.')
)
```

```{r checkbox, echo = FALSE}
question_checkbox(
  "Select all the toppings that belong on a Margherita Pizza:",
  answer("tomato", correct = TRUE),
  answer("mozzarella", correct = TRUE),
  answer("basil", correct = TRUE),
  answer("extra virgin olive oil", correct = TRUE),
  answer("pepperoni", message = "Great topping! ... just not on a Margherita Pizza"),
  answer("onions"),
  answer("bacon"),
  answer("spinach"),
  random_answer_order = TRUE,
  allow_retry = TRUE,
  try_again = "Be sure to select all toppings!"
)
```

```{r text_box, echo = FALSE}
question_text(
  "Please enter the word 'C0rrect' below:",
  answer("correct", message = "Don't forget to capitalize"),
  answer("c0rrect", message = "Don't forget to capitalize"),
  answer("Correct", message = "Is it really an 'o'?"),
  answer("C0rrect", correct = TRUE),
  allow_retry = TRUE
)
```

```{r numeric, echo = FALSE}
question_numeric(
 "What is pi rounded to 2 digits?",
 answer(3, message = "Don't forget to use the digits argument"),
 answer(3.1, message = "Too few digits"),
 answer(3.142, message = "Too many digits"),
 answer(3.14, correct = TRUE),
 allow_retry = TRUE,
 min = 3,
 max = 4,
 step = 0.01
)
```

```{r options, echo = FALSE}
question(
  "How many parameters are supplied in this question?",
  answer("1", message = "Really?"),
  answer("2"),
  answer("3"),
  answer("15", correct = TRUE, message = "Custom message here."),
  type = "learnr_text", # radio
  correct = "Question is correct!",
  try_again = "Try Again!",
  message = "Reminder to do something after answering the question...",
  post_message = "Message to be displayed after the correct answer is found",
  submit_button = "Submit Answer Here!",
  try_again_button = "Try Again Here!",
  allow_retry = TRUE,
  random_answer_order = TRUE,
  options = list(
    placeholder = "The answer is '15'",
    trim = TRUE
  )
)
```

```{r custom_class, echo = FALSE}
question_is_correct.always_correct <- function(question, value, ...) {
  learnr::mark_as(TRUE, messages = NULL)
}

registerS3method("question_is_correct", "always_correct", question_is_correct.always_correct)

ques <- question(
  "Custom Method",
  answer("answer", correct = TRUE),
  answer("also marked as correct", correct = FALSE),
  type = c("always_correct", "learnr_checkbox")
)
```

```{r sortable_question, echo = FALSE}
rank_ex <- sortable::question_rank(
  "Sort the first 5 letters",
  learnr::answer(LETTERS[1:5], correct = TRUE),
  learnr::answer(rev(LETTERS[1:5]), correct = FALSE, "Other direction!")
)
rank_ex
```

```{r}
apply_if <- function(x, p, f) {
 result <- vector(length = length(x))
 n <- 0
 for (i in seq_along(x)) {
 if (p(x[i])) {
 n <- n + 1
 result[n] <- f(x[i])
 }
 }
 head(result, n)
}
apply_if(1:8, function(x) x %% 2 == 0, function(x) x**2)
```

```{r power_cube}
power <- function(n) function(x,n) x**n

square(1:4,2)

cube(1:4,3)
```

```{r apply}
### apply
m <- matrix(1:9, nrow = 3, byrow = TRUE)
m

apply(m, 1, function(x) paste(x, collapse = ":")) # row-wise

apply(m, 2, function(x) paste(x, collapse = ":")) # column-wise

apply(m, c(1,2), function(x) paste(x, collapse = ":")) # Both

sumpow <- function(x, n) sum(x) ** n
apply(m, 1, sumpow,n = 2) # row - wise
apply(m, 2, sumpow, n = 2) # column - wise
```


```{r}
factorial <- function(n) {
function(n){
  key <- as.character(n)
  if (key %in% names(table)){
    print(paste("I have already computed the value for", n))
    table[[key]]
  }else{
    print(paste("Going to compute the value for", n))
    res <- n(f)
    print(paste("that turned out to be", res))
    table[key] <<- res
    print(table)
    res
  }  
  }
 if (n == 1) {
 1
 } else {
 n * factorial(n - 1)
 }
}

factorial(5)
```

```{r}
### **Exercise**
replace_outliers <- function(x, lower, upper) {
  x[x < lower | x > upper] <- NA
  return(x)
}

# Example usage
x <- c(1, 5, 10, 15, 20)
lower <- 5
upper <- 15

replace_outliers(x, lower, upper)
```

```{r}
apply_if <- function(v, dosomething, transform) {
  Map(function(x) if (dosomething(x)) transform(x) else x, v)
}

# Example usage
v <- seq(1:8)
unlist(apply_if(v, function(x) x %% 2 == 0, function(x) x**2))

v <- seq(1:10)
unlist(v * ifelse(v %% 2 == 0, v, 1))  # Squares even numbers, leaves odd numbers unchanged
```

```{r cir}
# Define the generic Shape class with default methods that raise errors

circumference <- function(shape) {
  stop("circumference() is not implemented for generic Shape")
}

area <- function(shape) {
  stop("area() is not implemented for generic Shape")
}

# Define a Circle class
Circle <- function(radius) {
  if (radius <= 0) stop("Radius must be positive")
  structure(list(radius = radius), class = "Circle")
}

# Implement circumference for Circle
circumference.Circle <- function(shape) {
  return(2 * pi * shape$radius)
}
```

```{r area}
# Implement area for Circle
area.Circle <- function(shape) {
  return(pi * shape$radius^2)
}

# Define a Rectangle class
Rectangle <- function(width, height) {
  if (width <= 0 || height <= 0) stop("Width and height must be positive")
  structure(list(width = width, height = height), class = "Rectangle")
}

# Implement circumference for Rectangle
circumference.Rectangle <- function(shape) {
  return(2 * (shape$width + shape$height))
}

# Implement area for Rectangle
area.Rectangle <- function(shape) {
  return(shape$width * shape$height)
}
```

```{r}
# Example usage
circle <- Circle(5)
cat("Circle circumference:", circumference.Circle(circle), "\n")
cat("Circle area:", area.Circle(circle), "\n")

rectangle <- Rectangle(4, 6)
cat("Rectangle circumference:",circumference.Rectangle(rectangle), "\n")
cat("Rectangle area:", area.Rectangle(rectangle), "\n")
```

```{r}
# Define a Polynomial class
Polynomial <- function(coefficients) {
  structure(list(coefficients = coefficients), class = "Polynomial")
}

# Evaluate the polynomial at a given point x
evaluate_polynomial <- function(poly, x) {
  if (!inherits(poly, "Polynomial")) stop("Input must be a Polynomial object")
  coefs <- poly$coefficients
  n <- length(coefs) - 1
  sum(coefs * x^(0:n))
}

# Find the roots of the polynomial
find_roots <- function(poly) {
  if (!inherits(poly, "Polynomial")) stop("Input must be a Polynomial object")
  coefs <- poly$coefficients
  degree <- length(coefs) - 1
  
  if (degree == 1) {
    # Linear case: ax + b = 0 => x = -b/a
    return(-coefs[1] / coefs[2])
  } else if (degree == 2) {
    # Quadratic case: ax^2 + bx + c = 0
    a <- coefs[3]
    b <- coefs[2]
    c <- coefs[1]
    discriminant <- b^2 - 4 * a * c
    
  if (discriminant < 0) {
      return(NULL)  # No real roots
    } else {
      return(c((-b + sqrt(discriminant)) / (2 * a), (-b - sqrt(discriminant)) / (2 * a)))
    }
  } else {
    # General case: Use uniroot on a function representing the polynomial
    poly_func <- function(x) evaluate_polynomial(poly, x)
    root <- tryCatch({
      uniroot(poly_func, lower = -100, upper = 100)$root
    }, error = function(e) NULL)
    return(root)
  }
}
```

```{r}
# Example usage
poly1 <- Polynomial(c(2, -3, 3))  # x^2 - 3x + 2
cat("Polynomial evaluated at x = 2:", evaluate_polynomial(poly1, 2), "\n")
cat("Polynomial roots:", find_roots(poly1), "\n")
```

